services:
  - name: speaksync-api
    type: web
    env: docker
    region: oregon      # or frankfurt/singapore
    plan: free
    dockerContext: ./backend          # path containing Dockerfile
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_BUCKET
        sync: false
      - key: AWS_REGION
        value: us-east-2
    healthCheckPath: /docs            # FastAPI Swagger → returns 200
